# Generated by Django 2.2 on 2021-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210814_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
