# Generated by Django 2.2 on 2021-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireArchitect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=120)),
                ('PlanDescription', models.TextField()),
                ('TimeLimit', models.IntegerField()),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=120)),
                ('PlanImage', models.ImageField(upload_to='')),
                ('RegularPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SalePrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('PlanFile', models.FileField(upload_to='')),
            ],
        ),
    ]
